services:
  target-nginx:
    image: nginx:alpine
    container_name: target-nginx
    networks:
      sentinel-net:
        ipv4_address: 172.28.0.10

  target-redis:
    image: redis:alpine
    container_name: target-redis
    networks:
      sentinel-net:
        ipv4_address: 172.28.0.20

  target-dvwa:
    image: vulnerables/web-dvwa
    container_name: target-dvwa
    networks:
      sentinel-net:
        ipv4_address: 172.28.0.30

  sentinel:
    build: .
    container_name: cerberus-sentinel
    ports:
      - "8080:8080"
    environment:
      - CERBERUS_PORT=8080
      - CERBERUS_SUBNET=172.28.0.0/24
      - CERBERUS_DISCOVERY_INTERVAL=30m
      - CERBERUS_VULN_INTERVAL=10m
      - CERBERUS_UNPRIVILEGED=false
      - CERBERUS_MOCK_DATA=true
    volumes:
      - sentinel-data:/app/data
    cap_add:
      - NET_RAW
      - NET_ADMIN
    networks:
      sentinel-net:
        ipv4_address: 172.28.0.5
    depends_on:
      - target-nginx
      - target-redis
      - target-dvwa

networks:
  sentinel-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24

volumes:
  sentinel-data:
    driver: local